"""Protocol interfaces for external providers and persistence."""

from __future__ import annotations

from typing import Any, Protocol, runtime_checkable

from bookshift.domain.models import LogicalBook, Position


@runtime_checkable
class AudiobookProvider(Protocol):
    def resolve_token(self) -> str: ...

    def get_progress(self, library_item_id: str) -> dict[str, Any] | None: ...

    def get_chapters(self, item_id: str) -> tuple[list[dict[str, Any]], dict[str, Any]]: ...

    def search_item(self, title: str, author_hint: str | None = None) -> dict[str, Any] | None: ...


@runtime_checkable
class EbookProvider(Protocol):
    def login(self) -> str: ...

    def get_progress(self, book_id: int) -> list[dict[str, Any]]: ...

    def get_file_progress(self, file_id: int) -> tuple[int, Any]: ...

    def update_progress(self, file_id: int, payload: dict[str, Any]) -> tuple[int, Any]: ...

    def find_book(self, title: str, author_hint: str | None = None) -> dict[str, Any] | None: ...

    def convert_position(
        self,
        mode: str,
        *,
        epub_path: str,
        extra_args: list[str],
        script_name: str,
        work_dir: str,
    ) -> dict[str, Any]: ...


@runtime_checkable
class AlignmentEngine(Protocol):
    def probe_worker(self, url: str | None = None) -> dict[str, Any]: ...

    def configure_whisper_url(self, url: str, *, dry_run: bool = False) -> dict[str, Any]: ...

    def dispatch_alignment(self, title: str, *, dry_run: bool = False) -> dict[str, Any]: ...

    def readaloud_status(self, title: str) -> dict[str, Any]: ...


@runtime_checkable
class StateRepository(Protocol):
    def connect(self) -> Any: ...

    def get_book(self, logical_book_id: int) -> dict[str, Any] | None: ...

    def save_book(self, logical_book_id: int, **fields: Any) -> dict[str, Any]: ...

    def list_active_books(self) -> list[dict[str, Any]]: ...

    def list_logical_books(self) -> list[dict[str, Any]]: ...

    def load_sync_cache_bundles(self) -> list[dict[str, Any]]: ...

    def migrate_schema(self) -> None: ...

    def mark_koreader_endpoint_ready(self, book_id: int, endpoint_url: str) -> None: ...

    def eligible_coarse_books(self) -> list[dict[str, Any]]: ...
